nome=input("qual seu nome ?")
endereço=input("qual seu endereço ?")
cidade=input("qual sua cidade ?")
cep=input("qual seu cep ?")
dianascimento=input("qual o dia de seu nascimento ?")
mesdenascimento=input("qual o mês de seu nascimento ?")
anodenascimento=input("qual o ano de seu nascimento ?")
print("seu nome é",nome)
print("sua endereço é",endereço)
print("sua cidade é",cidade)
print("seu cep é",cep")
print("seu dia de nascimento é",dianascimento)
